version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: tutor-link
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tutor-link
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
