version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: tutorlink
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tutorlink
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6373:6379"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
volumes:
  pgdata:
